/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_trizalio_ndk_test_MainScreen */

#ifndef _Included_com_example_trizalio_ndk_test_MainScreen
#define _Included_com_example_trizalio_ndk_test_MainScreen
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_trizalio_ndk_test_MainScreen
 * Method:    getMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_trizalio_ndk_1test_MainScreen_getMessage
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
